# dpkg --add-architecture i386
# apt-get update
# apt-get install wget lib32gcc1 lib32stdc++6 libcurl4-gnutls-dev:i386
# su - dst
# wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
# tar -xvzf steamcmd_linux.tar.gz
# mkdir server_dst


# Use steamcmd base image
FROM cm2network/steamcmd

# update apt database
RUN apt-get update

RUN mkdir ~/server_dst

RUN ./steamcmd.sh login anonymous force_install_dir ~/server_dst app_update 343050 validate

RUN 
